#ifndef LL_KEYLIST_H
#define LL_KEYLIST_H
// Function Keys
#define _F1             59
#define _F2             60
#define _F3             61
#define _F4             62
#define _F5             63
#define _F6             64
#define _F7             65
#define _F8             66
#define _F9             67
#define _F10            68
#define _F11            87
#define _F12            88

// System Keys
#define _ESC            2
#define _PRNT_SCRN      55
#define _PAUSE          29
#define _MACRO          86
#define _SCROLL_LOCK    70
#define _NUM_LOCK       69
#define _CAPS_LOCK      58
#define _L_SHIFT        42
#define _R_SHIFT        54
#define _SPACE          114
#define _ALT            112
#define _CTRL           58

#define _TAB            30
#define _ENTER          28
#define _BACKSPACE      14

// Cursor Control Keys
#define _HOME           142
#define _UP             144
#define _PGUP           146
#define _LEFT           150
#define _MIDDLE         152
#define _RIGHT          154
#define _END            158
#define _DOWN           160
#define _PGDN           162
#define _INS            164
#define _DEL            166
#endif


